@startuml

title List/Search Family History Entries - Level 2 View

actor Doctor as U
participant "Frontend" as web
participant "Express\nBackend" as api
database "Mongo\nDatabase" as db

U -> web : Picks attributes to search\nfamily history entries from\na medical record
activate U
activate web
web -> api : Picks attributes to search\nfamily history entries from\na medical record
activate api

api -> db : Get list of family\nhistory entries
activate db
db --> api : Family history\nentry list
deactivate db
api -> web : Return List
deactivate api
web -> U : Return List
deactivate web
deactivate U


@enduml