' 
' User Story: As a **Doctor**, I want to request an operation, so that the Patient has access to the necessary healthcare.
'
' Acceptance Criteria:
' 
' - Doctors can input operation details such as **Patient ID**, **Operation type**, **Priority**, **Date**, **Time** and **Request Status**.
' - A unique **Operation ID** is generated upon profile creation.
' - The system validates that the Patient ID and Operation type are valid.
' - The profile is stored securely in the system.

@startuml

title US 6-2-14 - Level 3 View

actor Admin as U
participant "«component»\doctor.component.html" as html
participant "«component»\doctor.component.ts" as ts

participant "«component»\n«C4 Container»\nBackend" as backend

U -> html : Starts process
activate U
activate html
activate ts

html -> ts : operationType()
ts --> html
html --> U

U -> html : Fills out form
html -> ts
ts -> ts : Verifies operationType validity
ts --> html
html --> U

U -> html : Submits form
html -> ts : onCreate()
ts -> backend: createOperationRequest()
activate backend
backend --> ts : Operation object
deactivate backend
ts --> html : success/error message
html --> U : show success/error message

@enduml