' 
' User Story: As a **staff**, I want to request an Staff, so that the Patient has access to the necessary healthcare.
'
' Acceptance Criteria:
' 
' - staffs can input Staff details such as **Patient ID**, **Staff type**, **Priority**, **Date**, **Time** and **Request Status**.
' - A unique **Staff ID** is generated upon profile creation.
' - The system validates that the Patient ID and Staff type are valid.
' - The profile is stored securely in the system.

@startuml

title US 6-2-10 - Level 3 View

actor Admin as U
participant "«component»\staff.component.html" as html
participant "«component»\staff.component.ts" as ts

participant "«component»\n«C4 Container»\nBackend" as backend

U -> html : Starts process
activate U
activate html
activate ts

html -> ts : staff()
ts --> html
html --> U

U -> html : Fills out form
html -> ts
ts -> ts : Verifies staff validity
ts --> html
html --> U

U -> html : Submits form
html -> ts : onCreate()
ts -> backend: createStaff()
activate backend
backend --> ts : Staff object
deactivate backend
ts --> html : success/error message
html --> U : show success/error message

@enduml