// <auto-generated />
using System;
using DDDSample1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations.DDDSample1Db
{
    [DbContext(typeof(DDDSample1DbContext))]
    partial class DDDSample1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DDDSample1.Domain.OperationRequests.OperationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("operationTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("patientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("priority")
                        .HasColumnType("longtext");

                    b.Property<int>("requestStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("staffId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("operationTypeId");

                    b.HasIndex("patientId");

                    b.HasIndex("staffId");

                    b.ToTable("OperationRequest", "projeto5sem");
                });

            modelBuilder.Entity("DDDSample1.Domain.OperationTypes.OperationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("anaesthesiaTime")
                        .HasColumnType("int");

                    b.Property<int?>("cleaningTime")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int?>("surgeryTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OperationType", "projeto5sem");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("2b4d426f-e775-42b1-b053-691a91b74ba2"),
========
                            Id = new Guid("978b1f44-6f15-4b40-9c6f-1235e8e50799"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Status = "ACTIVE",
                            name = "ACL Reconstruction"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("612897d6-e155-4837-a8bc-a76a795a2e8c"),
========
                            Id = new Guid("1036ef74-1fc0-43fd-af25-d28e9b7d7e24"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Status = "ACTIVE",
                            name = "Knee Replacement"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("9705d96e-b341-42ee-987d-180f33f8a5e1"),
========
                            Id = new Guid("55347851-39a1-4117-9b3d-ae0468e68abe"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Status = "ACTIVE",
                            name = "Shoulder Replacement"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("c94be47f-1d3d-4b61-91da-eef9a634419a"),
========
                            Id = new Guid("b520c722-ebbb-4409-9852-f5cbe062eaa7"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Status = "ACTIVE",
                            name = "Hip Replacement"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("68626bb6-8507-4a70-9ecf-45cdbff3f1d6"),
========
                            Id = new Guid("32b8a4da-5242-403d-81df-03b6b79aea2d"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Status = "ACTIVE",
                            name = "Meniscal Injury Treatment"
                        });
                });

            modelBuilder.Entity("DDDSample1.Domain.Patients.Allergy", b =>
                {
                    b.Property<Guid>("allergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PatientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("allergyName")
                        .HasColumnType("longtext");

                    b.HasKey("allergyId");

                    b.HasIndex("PatientId");

                    b.ToTable("Allergy");
                });

            modelBuilder.Entity("DDDSample1.Domain.Patients.Patient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MedicalRecordNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Patient", "projeto5sem");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = "8b813cf5-a7ef-4b58-b437-00ebea78a0f6",
========
                            Id = "1cb2b22e-45c4-4686-8166-c801351c15fd",
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            DateOfBirth = new DateOnly(2001, 10, 21),
                            Email = "patientA@hospital.com",
                            FullName = "João Camião",
                            Gender = "Male",
                            MedicalRecordNumber = "202410000001",
                            PhoneNumber = "910555111"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = "67f5ac88-8db2-4900-9665-ccd01b14108d",
========
                            Id = "803bbdd8-6b09-4b80-aef3-dc0397229a1c",
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            DateOfBirth = new DateOnly(1998, 5, 14),
                            Email = "patientB@hospital.com",
                            FullName = "Bruno Silva",
                            Gender = "Male",
                            MedicalRecordNumber = "202410000002",
                            PhoneNumber = "910555222"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = "27ec56a4-ebaf-43a3-96c1-4a0fab32175e",
========
                            Id = "1f9495cd-b6ad-4995-804b-f638e5253057",
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            DateOfBirth = new DateOnly(1995, 12, 30),
                            Email = "patientC@hospital.com",
                            FullName = "Carla Ferreira",
                            Gender = "Female",
                            MedicalRecordNumber = "202410000003",
                            PhoneNumber = "910555333"
                        });
                });

            modelBuilder.Entity("DDDSample1.Domain.Staffs.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<string>("staffRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Staff", "projeto5sem");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("94c80dfa-4c8c-4d21-bc29-47053fa17ac1"),
========
                            Id = new Guid("7d12e017-f06b-4723-8541-7f0b043cd23e"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            staffRole = "Admin"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("14d255ba-7535-490e-abbf-c3eadee1b692"),
========
                            Id = new Guid("dfa31c2f-9ca8-41ec-86d9-cf44f76be48b"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            staffRole = "Doctor"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("14626743-499d-4f69-bed5-0a234e0840ed"),
========
                            Id = new Guid("f9c03261-6822-4abc-9e04-400c19594486"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            staffRole = "Doctor"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("6d7e46e0-878b-450b-8fac-a3039a352374"),
========
                            Id = new Guid("6d795d46-4c78-4521-97b3-56b4ec721c16"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            staffRole = "Nurse"
                        },
                        new
                        {
<<<<<<<< HEAD:Backend/src/Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            Id = new Guid("6185d31b-39a4-4b01-8dd5-41e866fc048a"),
========
                            Id = new Guid("5c066848-2e40-4f96-9910-41e7ad69e524"),
>>>>>>>> fe98147 (Commit para cleaning):Migrations/DDDSample1Db/DDDSample1DbContextModelSnapshot.cs
                            staffRole = "Nurse"
                        });
                });

            modelBuilder.Entity("DDDSample1.Domain.OperationRequests.OperationRequest", b =>
                {
                    b.HasOne("DDDSample1.Domain.OperationTypes.OperationType", "operationType")
                        .WithMany("OperationRequests")
                        .HasForeignKey("operationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.Patients.Patient", "patient")
                        .WithMany("OperationRequests")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DDDSample1.Domain.Staffs.Staff", "staff")
                        .WithMany("OperationRequests")
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operationType");

                    b.Navigation("patient");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("DDDSample1.Domain.Patients.Allergy", b =>
                {
                    b.HasOne("DDDSample1.Domain.Patients.Patient", null)
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DDDSample1.Domain.OperationTypes.OperationType", b =>
                {
                    b.Navigation("OperationRequests");
                });

            modelBuilder.Entity("DDDSample1.Domain.Patients.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("OperationRequests");
                });

            modelBuilder.Entity("DDDSample1.Domain.Staffs.Staff", b =>
                {
                    b.Navigation("OperationRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
