' 
' User Story: As a **Admin**, I want to request an Staff, so that the Patient has access to the necessary healthcare.
'
' Acceptance Criteria:
' 
' - Admins can input Staff details such as **Patient ID**, **Staff type**, **Priority**, **Date**, **Time** and **Request Status**.
' - A unique **Staff ID** is generated upon profile creation.
' - The system validates that the Patient ID and Staff type are valid.
' - The profile is stored securely in the system.

@startuml

title US 6-2-10 - Level 1 View

actor Admin as U
participant "<<system>>\nHospital de Paranhos" as web

U -> web : Creates new Staff with its attributes
activate U
activate web
web -> web : Validades Staff
web -> web : Logs Staff creation
web -> U : Return Confirmation
deactivate web
deactivate U




@enduml