' 
' User Story: As a **Doctor**, I want to update an operation requisition, so that the Patient has access to the necessary healthcare.
'
' Acceptance Criteria:
' 
' - Doctors can **search for an operation** to edit.
' - Editable fields include priority, date and time.
' - The system logs all profile changes for auditing purposes.

@startuml

title US6.2.15 - Level 1 View

actor Doctor as U
participant "<<system>>\nHospital de Paranhos" as web

U -> web : Edits the attributes of a previously\nchosen Operation
activate U
activate web
alt if the Operation doesn't exist
web --> U : Error message
else 
web -> web : Validades changes
alt changed data is sensitive\n
end
web -> web : Logs all Operation changes
web -> U : Return Confirmation
deactivate web
deactivate U
end



@enduml