' 
' User Story: As a **Doctor**, I want to update an operation requisition, so that the Patient has access to the necessary healthcare.
'
' Acceptance Criteria:
' 
' - Doctors can **search for an operation** to edit.
' - Editable fields include priority, date and time.
' - The system logs all profile changes for auditing purposes.

@startuml

title US6.2.15 - Level 3 View - Frontend

actor Doctor as U
participant "«component»\doctor.component.html" as html
participant "«component»\doctor.component.ts" as ts

participant "«component»\n«C4 Container»\nBackend" as backend

U -> html : Starts process after\nselecting a Operation
activate U
activate html
activate ts

html -> ts : onEdit()
ts --> html
html --> U

U -> html : Picks what attributes they\nwant to edit and edits them
html -> ts
ts -> ts : Verifies Operation Type validity
ts --> html
html --> U

U -> html : Submits form
html -> ts : onUpdateSubmit()
ts -> backend: updateOperationRequest(this.selectedRequest.operationRequestId, priority, dateTime)
activate backend
backend --> ts : operation object
deactivate backend
ts --> html : success/error message
html --> U : show success/error message

@enduml