' 
' User Story: As an Admin, I want to add new types of operations, so that I can reflect the available medical procedures in the system.
'
' Acceptance Criteria:
' 
' - Admins can add new operation types with attributes like:
'   - Operation Name
'   - Required Staff by Specialization
'   - Estimated Duration
' - The system validates that the operation name is unique.
' - The system logs the creation of new operation types and makes them available for scheduling immediately.

@startuml

title US20-Container View

actor Admin as A
participant "<<system>>\nHealthcare System" as S

A -> S : Creates Operation Type with its attributes
activate A
activate S

S -> S : Validate operation Data
S -> S : Log operation creation

deactivate A


@enduml
