@startuml


actor Admin as A
participant "Frontend" as web
participant "Backend" as api
database "Database" as db

A -> web : Selectes Operation Type to Deactivate
activate A
activate web

web -> api : Selectes Operation Type to Deactivate
activate api

api -> api : Set Operation Type as Inactive
api -> db : Save Operation Type Changes
activate db
deactivate db
api -> api : Log Operation Type Deactivation
api -> web : Return Confirmation
deactivate api
web -> A : Return Confirmation
deactivate web
deactivate A

@enduml