# This workflow will build a TypeScript project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: express

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Express Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
    - name: Install dependencies
      run: npm install
      working-directory: ./ExpressBackend
    - name: Build
      run: npm run build 
      working-directory: ./ExpressBackend
    - name: Test
      run: npm run test
