# This workflow will build a TypeScript project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.0'
    - name: Install dependencies
      run: |
       npm install
       npm install three
      working-directory: ./HospitalApp
    - name: Build
      run: npm run build
      working-directory: ./HospitalApp
    #- name: Test
     # run: npm test
